name: CI # Nombre del workflow = un conjunto de tareas a ejecutar

on: [push] # Se ejecuta cuando hay un push a cualquier branch

jobs: # Defino los jobs, un conjunto de pasos
 sast_scan: # Defino un job puntual
   name: Run Bandit Scan # Nombre de este job en particular
   runs-on: ubuntu-latest # Se ejecuta en un runner (VM/Container) de Ubuntu última versión

   steps: # Defino los pasos a ejecutar en este job
   - name: Checkout code # Nombre el paso. Checkout es para copiar el código del repo al runner, pues es una máquina fresca/sin nada que se invoca para correr este job.
     uses: actions/checkout@v2 # defino qué hace el paso con "uses", aquí van las acciones de GitHub u otros proveedores.
                               # (under "actions/* reusable actions are hosted)
   - name: Set up Python # Como nada está instalado en el runner inicialmente, también debo instalar cuanta dependencia y software necesite para mi job
     uses: actions/setup-python@v2 # Paso que instala Python en el runner
     with:
       python-version: 3.8 # Le digo qué versión de Python quiero instalar, esta acción también se encuentra en el marketplace de acciones de la derecha

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
     run: bandit -ll -ii -r . -f json -o bandit-report.json

   - name: Upload Artifact
     uses: actions/upload-artifact@v3
     if: always()
     with:
      name: bandit-findings
      path: bandit-report.json

 image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Docker
     uses: docker-practice/actions-setup-docker@v1
     with:
      docker_version: '20.10.7'

   - name: Build Docker Image
     run: docker build -f Dockerfile -t myapp:latest .

   # - name: Docker Scout Scan
     # run: |
       # curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
       # sh install-scout.sh
       # echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
       # docker scout quickview
       # docker scout cves

   - name: Docker Scout Scan
     uses: docker/scout-action@v1.0.9
     with:
       dockerhub-user: ${{ secrets.REPO_USER }}
       dockerhub-password: ${{ secrets.REPO_PWD }}
       command: quickview,cves
       only-severities: critical,high
       sarif-file: scout-report.sarif

   - name: Upload Artifact
     uses: actions/upload-artifact@v3
     if: always()
     with:
       name: docker-scout-findings
       path: scout-report.sarif




   

   
